name: code checks
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run greeting script
        run: |
          echo "Hello, world!"
          echo "This is a simple greeting script."
          echo "Have a great day!"